DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `NAME` varchar(32) DEFAULT NULL COMMENT '姓名',
  `PHONE` char(11) DEFAULT NULL COMMENT '手机号码',
  `TELEPHONE` varchar(16) DEFAULT NULL COMMENT '住宅电话',
  `ADDRESS` varchar(64) DEFAULT NULL COMMENT '联系地址',
  `ENABLED` tinyint(1) DEFAULT '1' COMMENT '是否有效',
  `USERNAME` varchar(255) DEFAULT NULL COMMENT '用户名',
  `PASSWORD` varchar(255) DEFAULT NULL COMMENT '密码',
  `EMAIL` varchar(50) DEFAULT NULL COMMENT '邮箱',
  `SEX` int(1) DEFAULT NULL COMMENT '性别',
  `PROVINCE` varchar(10) DEFAULT NULL COMMENT '省',
  `CITY` varchar(10) DEFAULT NULL COMMENT '市',
  `DISTRICT` varchar(10) DEFAULT NULL COMMENT '区',
  `ENTERPRISE_ID` int(11) DEFAULT NULL COMMENT '企业id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE `ROLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(64) DEFAULT NULL COMMENT '权限名称',
  `NAMEZH` varchar(64) DEFAULT NULL COMMENT '角色名称',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `USER_OF_ROLE`;
CREATE TABLE `USER_OF_ROLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERID` int(11) DEFAULT NULL COMMENT '用户ID',
  `ROLEID` int(11) DEFAULT NULL COMMENT '权限ID ',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `MENU`;
CREATE TABLE `MENU` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `URL` varchar(64) DEFAULT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  `ICONCLS` varchar(64) DEFAULT NULL,
  `PARENTID` int(11) DEFAULT NULL,
  `ENABLED` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `ROLE_OF_MENU`;
CREATE TABLE `ROLE_OF_MENU` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MENUID` int(11) DEFAULT NULL COMMENT 'MENU_ID',
  `ROLEID` int(11) DEFAULT NULL COMMENT '权限ID ',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8;









